name: Push mentor-ai.js to S3

on:
  release:
    types:
      - created
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          repository: iblai/iblai-web-mentor
          token: ${{ secrets.GIT_TOKEN }}
          ref: develop

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: NPM run build & sync to s3
        run: |
          cd $GITHUB_WORKSPACE
          npm install
          npm i -g typescript
          npm run build
          cd dist
          aws s3 cp mentor-ai.js s3://mentor-ai/

      - name: Latest iblai-web-mentor versionId
        id: get-version
        run: |
          echo "Latest iblai-web-mentor version ID is $(aws s3api list-object-versions --bucket mentor-ai --query "Versions[0].VersionId" --output text)"
